services:
  app:
    container_name: fastapi
    build:
      context: ..
      dockerfile: provision/Dockerfile.dev
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ../app.db:/app/app.db
      - ../src:/app/src
    env_file:
      - ../.env
