"""Create training absence schemas

Revision ID: 2738c641d6bc
Revises: 6e1c9c438cc9
Create Date: 2026-03-06 22:16:51.487539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2738c641d6bc"
down_revision: Union[str, Sequence[str], None] = "6e1c9c438cc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trainer_id", sa.Integer(), nullable=True),
        sa.Column("session_start", sa.Time(), nullable=False),
        sa.Column("session_duration", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_sessions_id"), "training_sessions", ["id"], unique=False
    )
    op.create_table(
        "absences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("training_session_id", sa.Integer(), nullable=True),
        sa.Column("trainee_id", sa.Integer(), nullable=True),
        sa.Column("absence_date", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trainee_id"],
            ["user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_session_id"],
            ["training_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_absences_id"), "absences", ["id"], unique=False)
    op.create_table(
        "training_session_trainees",
        sa.Column("training_session_id", sa.Integer(), nullable=False),
        sa.Column("trainee_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trainee_id"],
            ["user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["training_session_id"],
            ["training_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("training_session_id", "trainee_id"),
    )
    op.create_table(
        "substition_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("absence_id", sa.Integer(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["absence_id"],
            ["absences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["user_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_substition_requests_id"), "substition_requests", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_substition_requests_id"), table_name="substition_requests")
    op.drop_table("substition_requests")
    op.drop_table("training_session_trainees")
    op.drop_index(op.f("ix_absences_id"), table_name="absences")
    op.drop_table("absences")
    op.drop_index(op.f("ix_training_sessions_id"), table_name="training_sessions")
    op.drop_table("training_sessions")
    # ### end Alembic commands ###
