"""Update user schema for tennis club app

Revision ID: c00b79e3f250
Revises: 4ea94fd957d5
Create Date: 2026-03-06 21:34:49.359991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c00b79e3f250'
down_revision: Union[str, Sequence[str], None] = '4ea94fd957d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_accounts', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('user_accounts', sa.Column('looking_for_playmate', sa.Boolean(), nullable=False))
    op.add_column('user_accounts', sa.Column('tennis_availability', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_accounts', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_accounts', sa.Column('tennis_ranking', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_accounts', sa.Column('tennis_ranking_comment', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'tennis_ranking_comment')
    op.drop_column('user_accounts', 'tennis_ranking')
    op.drop_column('user_accounts', 'phone_number')
    op.drop_column('user_accounts', 'tennis_availability')
    op.drop_column('user_accounts', 'looking_for_playmate')
    op.drop_column('user_accounts', 'birth_date')
    op.drop_column('user_accounts', 'gender')
    # ### end Alembic commands ###
