"""Create request schema

Revision ID: c50db4b191f7
Revises: b3c4d5e6f7a8
Create Date: 2026-04-03 12:07:04.340182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c50db4b191f7"
down_revision: Union[str, Sequence[str], None] = "b3c4d5e6f7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "substitution_requests",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("absence_date", sa.DateTime(), nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "absence_date", "requester_id", name="uq_substitution_request"
        ),
    )
    with op.batch_alter_table("user_accounts") as batch_op:
        batch_op.alter_column(
            "email",
            existing_type=sa.String(30),
            type_=sa.String(50),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_accounts") as batch_op:
        batch_op.alter_column(
            "email",
            existing_type=sa.String(50),
            type_=sa.String(30),
            existing_nullable=False,
        )
    op.drop_table("substitution_requests")
    # ### end Alembic commands ###
