name: Lint

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  Code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/ruff-action@v3
        name: Lint with ruff
        with:
            src: "./src"
